### ISSUE TITLE
What about a daemon?

### ISSUE THREAD

**Issue by soyuka** [dat-land/dat-desktop#434]
Hi there!

I'm currently hacking around with dat and my goal is to use dat on distant servers rather then at home.

Today, there are 2 user interfaces to manage dats:

1. `dat-cli` 
2. `dat-desktop` (uses `multidat`)

I want to be able to manage lists, and it felt natural to build a `daemon` [poc here](https://github.com/soyuka/dat-daemon). 

It got me thinking into having a distant web interface. Dat-desktop is good and has everything one may need. 

Would you be interested in a patch that separates the `client` (html, css, front js) from `electron`?

To ease further usage, do you think that a daemon would be a viable option for `dat-desktop`'s "server" side so that it could be used anywhere? The `daemon` would be responsible of managing `dats` elements (add, remove, list, stat). 

Everything could go through the daemon (for electron `net.connect` + `dat-web` - maybe fork the daemon, possibility to share with a closed app, quick-menu etc.).

**Comment by karissa** [comment]
That sounds like a great idea.

**Comment by soyuka** [comment]
I see that you run the tests on node 7.0, though it's neither LTS nor Current.
Do you wish to support LTS? What about moving to Current so that we can use `async/await`?

To start working on this, IMHO, the code responsible to manage the *dat-list* should be a module.

I've two suggestions for what could be done:

1. don't use any tcp from electron, rather directly use the *dat-list* module with the ipc bus
2. use a daemon from electron with a bridge ipc => tcp

In both case, having this *dat-list* module this would ease the implementation of a daemon. 

WDYT?

**Comment by karissa** [comment]
Yeah, love this dat-list idea!

**Comment by soyuka** [comment]
> Do you wish to support LTS? What about moving to Current so that we can use async/await?

:stuck_out_tongue:

**Comment by joehand** [comment]
> Do you wish to support LTS? What about moving to Current so that we can use async/await?

Ya, in general we target anything covered in Node's LTS or maintenance (node 4, 6, 8). Moving test targets from 7 -> 8 sounds good for this project and we've tried to do that in general, just a bit behind here. Because this package gets bundled and distributed, it can use anything. But any modules that will be used in other projects should be able to be used in older node versions. This would likely apply, for example, to the daemon.

You're free to use new js features but be warned that some of use are still on node 6 and don't really use async/await yet, so it may impact contributions and and PR reviews. Optimally, you'd provide a way to build with older node versions for development.

Definitely excited about idea of a daemon! Another use case I'd be interested for this is connecting to dat via other languages, like python. Also check out [datd](https://github.com/wesleytodd/datd) for a bit of prior art.

**Comment by soyuka** [comment]
Thanks, exactly what I needed. 

Thanks about the `datd` link. However, the `dat-desktop` code is a little bit cleaner/simpler regarding the list management (uses only `multidat` et `toiletdb`). Also, he uses `class` and `Symbol`. Thus, I will see how I can reuse the code from `dat-desktop` to build those things!

I'm just not sure yet if `dat-desktop` should use a daemon or directly the high-level list management module.
